### ISSUE TITLE
Python Support module 

### ISSUE THREAD

**Issue by VPyt** [sjlongland/adv950#2]

**Comment by sjlongland** [comment]
On 18/10/23 19:52, VPyt wrote:
> Which Python module is required to be installed for using Advantech 
> XNaviDAQ PCI card in Windows Environment? Already installed hardware 
> device drivers using DAXNavi SDK. From where to get this module?

Wouldn't have a bloody clue, I don't muck around with legacy operating 
systems.
-- 
Stuart Longland (aka Redhatter, VK4MSL)

I haven't lost my mind...
   ...it's backed up on a tape somewhere.
